-- Runtime Benchmark - Declarative UI
-- Chrome only - benchmark entities spawned dynamically by behavior

return {
  id = "root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 720,
  shellLayout = {
    mode = "fill",
    designW = 1280,
    designH = 720,
  },
  style = {
    bg = 0xff111827,
  },
  behavior = "ui/behaviors/main.lua",
  children = {
    -- Header bar
    {
      id = "header",
      type = "Panel",
      x = 0,
      y = 0,
      w = 1280,
      h = 64,
      style = {
        bg = 0xff1f2937,
        radius = 0,
      },
    },
    -- Spawn buttons
    {
      id = "spawn1k",
      type = "Button",
      x = 8,
      y = 8,
      w = 86,
      h = 22,
      props = { label = "Spawn 1k" },
      style = { bg = 0xff334155, fontSize = 11 },
    },
    {
      id = "spawn5k",
      type = "Button",
      x = 100,
      y = 8,
      w = 86,
      h = 22,
      props = { label = "Spawn 5k" },
      style = { bg = 0xff334155, fontSize = 11 },
    },
    {
      id = "spawn10k",
      type = "Button",
      x = 192,
      y = 8,
      w = 86,
      h = 22,
      props = { label = "Spawn 10k" },
      style = { bg = 0xff334155, fontSize = 11 },
    },
    {
      id = "spawn50k",
      type = "Button",
      x = 284,
      y = 8,
      w = 86,
      h = 22,
      props = { label = "Spawn 50k" },
      style = { bg = 0xff334155, fontSize = 11 },
    },
    -- Control buttons
    {
      id = "clearBtn",
      type = "Button",
      x = 376,
      y = 8,
      w = 70,
      h = 22,
      props = { label = "Clear" },
      style = { bg = 0xff7f1d1d, fontSize = 11 },
    },
    {
      id = "animBtn",
      type = "Button",
      x = 452,
      y = 8,
      w = 92,
      h = 22,
      props = { label = "Anim: OFF" },
      style = { bg = 0xff2563eb, fontSize = 11 },
    },
    -- Stats labels
    {
      id = "statsLabel",
      type = "Label",
      x = 8,
      y = 34,
      w = 600,
      h = 20,
      props = { text = "Ready. 0 nodes." },
      style = {
        colour = 0xffffffff,
        fontSize = 14,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "animLabel",
      type = "Label",
      x = 620,
      y = 34,
      w = 200,
      h = 20,
      props = { text = "Anim: 0.00 ms" },
      style = {
        colour = 0xff93c5fd,
        fontSize = 14,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "fpsLabel",
      type = "Label",
      x = 1160,
      y = 8,
      w = 112,
      h = 20,
      props = { text = "FPS: 0" },
      style = {
        colour = 0xff86efac,
        fontSize = 14,
        justification = Justify.centredRight,
      },
    },
    -- Viewport where benchmark nodes are spawned
    {
      id = "viewport",
      type = "Panel",
      x = 0,
      y = 64,
      w = 1280,
      h = 656,
      style = {
        bg = 0xff020617,
        border = 0xff334155,
        borderWidth = 1,
        radius = 0,
      },
    },
  },
}
