return {
  id = "root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 720,
  style = {
    bg = 0xff060b16,
  },
  behavior = "ui/behaviors/donut_view.lua",
  children = {},
  components = {
    {
      id = "vocal_fx",
      x = 0,
      y = 0,
      w = 1280,
      h = 170,
      behavior = "ui/behaviors/donut_vocal_fx.lua",
      ref = "ui/components/donut_vocal_fx.ui.lua",
    },
    {
      id = "layer0",
      x = 0,
      y = 178,
      w = 636,
      h = 172,
      props = { layerIndex = 0 },
      behavior = "ui/behaviors/donut_layer_card.lua",
      ref = "ui/components/donut_layer_card.ui.lua",
    },
    {
      id = "layer1",
      x = 644,
      y = 178,
      w = 636,
      h = 172,
      props = { layerIndex = 1 },
      behavior = "ui/behaviors/donut_layer_card.lua",
      ref = "ui/components/donut_layer_card.ui.lua",
    },
    {
      id = "layer2",
      x = 0,
      y = 358,
      w = 636,
      h = 172,
      props = { layerIndex = 2 },
      behavior = "ui/behaviors/donut_layer_card.lua",
      ref = "ui/components/donut_layer_card.ui.lua",
    },
    {
      id = "layer3",
      x = 644,
      y = 358,
      w = 636,
      h = 172,
      props = { layerIndex = 3 },
      behavior = "ui/behaviors/donut_layer_card.lua",
      ref = "ui/components/donut_layer_card.ui.lua",
    },
  },
}
