return {
  id = "root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 720,
  style = {
    bg = 4278849306,
  },
  behavior = "ui/behaviors/looper_view.lua",
  children = {},
  components = {
    {
      id = "layer0",
      x = 0,
      y = 0,
      w = 1280,
      h = 120,
      props = { layerIndex = 0 },
      behavior = "ui/behaviors/looper_layer_strip.lua",
      ref = "ui/components/looper_layer_strip.ui.lua",
    },
    {
      id = "layer1",
      x = 0,
      y = 126,
      w = 1280,
      h = 120,
      props = { layerIndex = 1 },
      behavior = "ui/behaviors/looper_layer_strip.lua",
      ref = "ui/components/looper_layer_strip.ui.lua",
    },
    {
      id = "layer2",
      x = 0,
      y = 252,
      w = 1280,
      h = 120,
      props = { layerIndex = 2 },
      behavior = "ui/behaviors/looper_layer_strip.lua",
      ref = "ui/components/looper_layer_strip.ui.lua",
    },
    {
      id = "layer3",
      x = 0,
      y = 378,
      w = 1280,
      h = 120,
      props = { layerIndex = 3 },
      behavior = "ui/behaviors/looper_layer_strip.lua",
      ref = "ui/components/looper_layer_strip.ui.lua",
    },
  },
}
