-- NOTE: The rack shell accent bars/colour strips in this file are temporary debug visuals.
-- They are only here to make shell boundaries obvious while the rack-module surface is being built.
-- They are NOT the agreed final rack card visual language and should be revisited when the
-- shell styling is properly designed/refactored.

local PaginationDots = require("components.pagination_dots")

local function paletteCard(props)
  local accent = props.accentColor or 0xff64748b
  local left = tonumber(props.left) or 12
  local top = tonumber(props.top) or 54
  local width = tonumber(props.width) or 164
  local height = tonumber(props.height) or 84
  local name = tostring(props.name or "MODULE")
  local hint = tostring(props.hint or "")
  local ports = tostring(props.ports or "")
  local compact = height <= 68
  local inset = compact and 8 or 10
  local accentH = compact and 4 or 6
  local nameTop = compact and 10 or 14
  local portsTop = compact and 27 or 34
  local hintTop = compact and 41 or 50
  local nameFont = compact and 10 or 11
  local hintFont = compact and 8 or 9
  local portsFont = compact and 8 or 9

  local card = {
    id = props.id,
    type = "Panel",
    x = 0, y = 0, w = width, h = height,
    style = {
      bg = 0xff121a2f,
      border = 0xff1f2b4d,
      borderWidth = 1,
      radius = 0,
    },
    props = { interceptsMouse = true },
    children = {
      {
        id = props.accentId,
        type = "Panel",
        x = 0, y = 0, w = width, h = accentH,
        layout = { mode = "hybrid", left = 0, top = 0, right = 0, height = accentH },
        style = { bg = accent, radius = 0 },
        props = { interceptsMouse = false },
      },
      {
        id = props.nameId,
        type = "Label",
        x = inset, y = nameTop, w = math.max(32, width - (inset * 2)), h = 14,
        layout = { mode = "hybrid", left = inset, top = nameTop, right = inset, height = 14 },
        props = { text = name },
        style = { colour = 0xffffffff, fontSize = nameFont },
      },
      {
        id = props.portsId,
        type = "Label",
        x = inset, y = portsTop, w = math.max(32, width - (inset * 2)), h = 12,
        layout = { mode = "hybrid", left = inset, top = portsTop, right = inset, height = 12 },
        props = { text = ports },
        style = { colour = 0xff94a3b8, fontSize = portsFont },
      },
      {
        id = props.hintId,
        type = "Label",
        x = inset, y = hintTop, w = math.max(32, width - (inset * 2)), h = 10,
        layout = { mode = "hybrid", left = inset, top = hintTop, right = inset, height = 10 },
        props = { text = hint },
        style = { colour = 0xff64748b, fontSize = hintFont },
      },
    },
  }

  if type(props.layoutChild) == "table" then
    card.layoutChild = props.layoutChild
  else
    card.layout = { mode = "hybrid", left = left, top = top, width = width, height = height }
  end

  return card
end

return {
  id = "midisynth_root",
  type = "Panel",
  x = 0, y = 0, w = 1280, h = 686,
  style = { bg = 0xff0b1220 },
  behavior = "ui/behaviors/midisynth.lua",
  children = {
    {
      id = "mainStack",
      type = "Panel",
      x = 0, y = 0, w = 1280, h = 686,
                  style = { bg = 0x00000000 },
                  props = { interceptsMouse = true },
      layout = {
        mode = "stack-y",
        padding = { 0, 0, 0, 0 },
        gap = 0,
        align = "stretch",
      },
      children = {
        {
          id = "content_rows",
          type = "Panel",
          x = 0, y = 0, w = 1280, h = 452,
          layoutChild = { order = 1, grow = 0, shrink = 0, basisH = 452, minH = 452, maxH = 452 },
          style = {
            bg = 0xff0f1726,
          },
          props = { interceptsMouse = false },
          layout = {
            mode = "stack-y",
            gap = 12,
            align = "stretch",
          },
          children = {
            (require("components/rack_container")),
            {
              id = "patchViewToggle",
              type = "Button",
              x = 1180, y = 0, w = 60, h = 24,
              layoutChild = { position = "absolute" },
              props = { label = "PATCH" },
              style = { bg = 0xff1e293b, border = 0xff38bdf8, borderWidth = 1, radius = 0, fontSize = 10 },
            },
          },
        },
        {
          id = "keyboardPanel",
          type = "Panel",
          x = 0, y = 0, w = 1248, h = 44,
          layoutChild = { order = 2, grow = 0, shrink = 0, basisH = 44, minH = 44 },
          style = { bg = 0xff11172a },
          props = { interceptsMouse = false },
          layout = {
            mode = "stack-y",
            padding = { 4, 16, 4, 16 },
            gap = 0,
            align = "stretch",
          },
          children = {
            {
              id = "utilitySplitArea",
              type = "Panel",
              x = 0, y = 0, w = 1216, h = 120,
              layoutChild = { order = 1, grow = 1, shrink = 1, basisH = 120, minH = 0 },
              style = { bg = 0xff0d1420, border = 0xff1f2937, borderWidth = 1, radius = 0 },
              props = { interceptsMouse = false },
              layout = {
                mode = "stack-y",
                padding = { 4, 8, 4, 8 },
                gap = 4,
                align = "stretch",
              },
              children = {
                {
                  id = "utilityTopBar",
                  type = "Panel",
                  x = 0, y = 0, w = 1196, h = 20,
                  layoutChild = { order = 1, grow = 0, shrink = 0, basisH = 20, minH = 20, maxH = 20 },
                  style = { bg = 0x00000000 },
                  props = { interceptsMouse = false },
                  layout = {
                    mode = "stack-x",
                    gap = 10,
                    align = "center",
                  },
                  children = {
                    {
                      id = "paletteTitle",
                      type = "Label",
                      x = 0, y = 0, w = 120, h = 18,
                      layoutChild = { basisW = 120, shrink = 0, alignSelf = "center" },
                      props = { text = "Modules" },
                      style = { colour = 0xffe2e8f0, fontSize = 12 },
                    },
                    {
                      id = "utilityTopBarSelected",
                      type = "Label",
                      x = 0, y = 0, w = 200, h = 16,
                      layoutChild = { basisW = 200, shrink = 1, alignSelf = "center" },
                      props = { text = "ADSR" },
                      style = { colour = 0xffcbd5e1, fontSize = 10 },
                    },
                    {
                      id = "utilityTopBarSpacer",
                      type = "Panel",
                      x = 0, y = 0, w = 600, h = 1,
                      layoutChild = { grow = 1, shrink = 1, alignSelf = "center" },
                      style = { bg = 0x00000000 },
                      props = { interceptsMouse = false },
                    },
                    {
                      id = "palettePagePrev",
                      type = "Button",
                      x = 0, y = 0, w = 24, h = 18,
                      layoutChild = { basisW = 24, shrink = 0, alignSelf = "center" },
                      props = { label = "^" },
                      style = { bg = 0xff0d1420, hoverBg = 0xff16233a, colour = 0xffcbd5e1, border = 0xff1f2b4d, borderWidth = 1, radius = 0, fontSize = 9 },
                    },
                    {
                      id = "palettePageLabel",
                      type = "Label",
                      x = 0, y = 0, w = 44, h = 16,
                      layoutChild = { basisW = 44, shrink = 0, alignSelf = "center" },
                      props = { text = "1/1" },
                      style = { colour = 0xff94a3b8, fontSize = 9 },
                    },
                    {
                      id = "palettePageNext",
                      type = "Button",
                      x = 0, y = 0, w = 24, h = 18,
                      layoutChild = { basisW = 24, shrink = 0, alignSelf = "center" },
                      props = { label = "v" },
                      style = { bg = 0xff0d1420, hoverBg = 0xff16233a, colour = 0xffcbd5e1, border = 0xff1f2b4d, borderWidth = 1, radius = 0, fontSize = 9 },
                    },
                  },
                },
                {
                  id = "utilityBrowserBody",
                  type = "Panel",
                  x = 0, y = 0, w = 1196, h = 136,
                  layoutChild = { order = 2, grow = 1, shrink = 1, basisH = 136, minH = 96 },
                  style = { bg = 0x00000000 },
                  props = { interceptsMouse = false },
                  layout = {
                    mode = "stack-x",
                    gap = 10,
                    align = "stretch",
                  },
                  children = {
                    {
                      id = "utilityNavRail",
                      type = "Panel",
                      x = 0, y = 0, w = 168, h = 136,
                      layoutChild = { basisW = 168, minW = 168, maxW = 168, shrink = 0 },
                      style = { bg = 0x00000000, border = 0x00000000, borderWidth = 0, radius = 0 },
                      props = { interceptsMouse = false },
                      layout = {
                        mode = "stack-y",
                        padding = { 8, 8, 8, 8 },
                        gap = 6,
                        align = "stretch",
                      },
                      children = {
                        {
                          id = "utilitySearchPanel",
                          type = "Panel",
                          x = 0, y = 0, w = 152, h = 24,
                          layoutChild = { basisH = 24, shrink = 0 },
                          style = { bg = 0xff0f172a, radius = 4 },
                          props = { interceptsMouse = true },
                          children = {
                            {
                              id = "utilitySearchText",
                              type = "Label",
                              x = 8, y = 5, w = 136, h = 14,
                              layout = { mode = "hybrid", left = 8, top = 5, right = 8, height = 14 },
                              props = { text = "Search modules..." },
                              style = { colour = 0xff64748b, fontSize = 9 },
                            },
                          },
                        },
                        {
                          id = "utilityTagRow",
                          type = "Panel",
                          x = 0, y = 0, w = 152, h = 24,
                          layoutChild = { basisH = 24, shrink = 0 },
                          style = { bg = 0x00000000 },
                          props = { interceptsMouse = false },
                          layout = {
                            mode = "stack-x",
                            padding = { 0, 0, 0, 0 },
                            gap = 4,
                            align = "center",
                          },
                          children = {
                            { id = "utilityTagAll", type = "Button", x = 0, y = 0, w = 32, h = 20, layoutChild = { basisW = 32, shrink = 0 }, props = { label = "All" }, style = { bg = 0xff334155, hoverBg = 0xff475569, colour = 0xfff1f5f9, border = 0xff334155, borderWidth = 1, radius = 4, fontSize = 9 } },
                            { id = "utilityTagVoice", type = "Button", x = 0, y = 0, w = 36, h = 20, layoutChild = { basisW = 36, shrink = 0 }, props = { label = "Voice" }, style = { bg = 0x00000000, hoverBg = 0xff1e293b, colour = 0xff94a3b8, border = 0xff1e293b, borderWidth = 1, radius = 4, fontSize = 9 } },
                            { id = "utilityTagAudio", type = "Button", x = 0, y = 0, w = 36, h = 20, layoutChild = { basisW = 36, shrink = 0 }, props = { label = "Audio" }, style = { bg = 0x00000000, hoverBg = 0xff1e293b, colour = 0xff94a3b8, border = 0xff1e293b, borderWidth = 1, radius = 4, fontSize = 9 } },
                            { id = "utilityTagFx", type = "Button", x = 0, y = 0, w = 28, h = 20, layoutChild = { basisW = 28, shrink = 0 }, props = { label = "FX" }, style = { bg = 0x00000000, hoverBg = 0xff1e293b, colour = 0xff94a3b8, border = 0xff1e293b, borderWidth = 1, radius = 4, fontSize = 9 } },
                            { id = "utilityTagMod", type = "Button", x = 0, y = 0, w = 32, h = 20, layoutChild = { basisW = 32, shrink = 0 }, props = { label = "Mod" }, style = { bg = 0x00000000, hoverBg = 0xff1e293b, colour = 0xff94a3b8, border = 0xff1e293b, borderWidth = 1, radius = 4, fontSize = 9 } },
                          },
                        },
                      },
                    },
                    {
                      id = "paletteStrip",
                      type = "Panel",
                      x = 0, y = 0, w = 760, h = 136,
                      layoutChild = { order = 2, grow = 1, shrink = 1 },
                      style = { bg = 0x00000000 },
                      props = { interceptsMouse = true },
                      children = {
                        {
                          id = "paletteScrollTrack",
                          type = "Panel",
                          x = 0, y = 0, w = 4, h = 72,
                          layout = { mode = "hybrid", right = 3, top = 8, bottom = 8, width = 4 },
                          style = { bg = 0xff111827, radius = 0 },
                          props = { interceptsMouse = false },
                          children = {
                            {
                              id = "paletteScrollThumb",
                              type = "Panel",
                              x = 0, y = 0, w = 4, h = 24,
                              layout = { mode = "hybrid", left = 0, top = 0, width = 4, height = 24 },
                              style = { bg = 0xff475569, radius = 0 },
                              props = { interceptsMouse = false },
                            },
                          },
                        },
                        {
                          id = "paletteStripContent",
                          type = "Panel",
                          x = 0, y = 0, w = 760, h = 136,
                          layout = { mode = "hybrid", left = 0, top = 0, right = 0, bottom = 0 },
                          style = { bg = 0x00000000 },
                          props = { interceptsMouse = false, clip = true },
                          children = {
                            {
                              id = "paletteStripRow",
                              type = "Panel",
                              x = 0, y = 0, w = 760, h = 136,
                              layout = { mode = "hybrid", left = 0, top = 0, right = 0, bottom = 0 },
                              style = { bg = 0x00000000 },
                              props = { interceptsMouse = false },
                              children = {
                                paletteCard {
                                  id = "palettePlaceholderCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff64748b,
                                  name = "SLOT",
                                  hint = "",
                                  ports = "IN  ->  OUT",
                                  deleteStubId = "palettePlaceholderDeleteStub",
                                  accentId = "palettePlaceholderAccent",
                                  resizeStubId = "palettePlaceholderResizeStub",
                                  nameId = "palettePlaceholderName",
                                  hintId = "palettePlaceholderHint",
                                  portsId = "palettePlaceholderPorts",
                                  layoutChild = { order = 1, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteAdsrCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xfffda4af,
                                  name = "ADSR",
                                  hint = "",
                                  ports = "MIDI  ->  VOICE",
                                  deleteStubId = "paletteAdsrDeleteStub",
                                  accentId = "paletteAdsrAccent",
                                  resizeStubId = "paletteAdsrResizeStub",
                                  nameId = "paletteAdsrName",
                                  hintId = "paletteAdsrHint",
                                  portsId = "paletteAdsrPorts",
                                  layoutChild = { order = 2, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteArpCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xfff59e0b,
                                  name = "ARP",
                                  hint = "",
                                  ports = "VOICE  ->  VOICE",
                                  deleteStubId = "paletteArpDeleteStub",
                                  accentId = "paletteArpAccent",
                                  resizeStubId = "paletteArpResizeStub",
                                  nameId = "paletteArpName",
                                  hintId = "paletteArpHint",
                                  portsId = "paletteArpPorts",
                                  layoutChild = { order = 3, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteTransposeCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff22c55e,
                                  name = "TRANSPOSE",
                                  hint = "",
                                  ports = "VOICE  ->  VOICE",
                                  deleteStubId = "paletteTransposeDeleteStub",
                                  accentId = "paletteTransposeAccent",
                                  resizeStubId = "paletteTransposeResizeStub",
                                  nameId = "paletteTransposeName",
                                  hintId = "paletteTransposeHint",
                                  portsId = "paletteTransposePorts",
                                  layoutChild = { order = 4, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteVelocityMapperCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff4ade80,
                                  name = "VELOCITY",
                                  hint = "",
                                  ports = "VOICE  ->  VOICE",
                                  deleteStubId = "paletteVelocityMapperDeleteStub",
                                  accentId = "paletteVelocityMapperAccent",
                                  resizeStubId = "paletteVelocityMapperResizeStub",
                                  nameId = "paletteVelocityMapperName",
                                  hintId = "paletteVelocityMapperHint",
                                  portsId = "paletteVelocityMapperPorts",
                                  layoutChild = { order = 5, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteScaleQuantizerCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff22c55e,
                                  name = "QUANT",
                                  hint = "",
                                  ports = "VOICE  ->  VOICE",
                                  deleteStubId = "paletteScaleQuantizerDeleteStub",
                                  accentId = "paletteScaleQuantizerAccent",
                                  resizeStubId = "paletteScaleQuantizerResizeStub",
                                  nameId = "paletteScaleQuantizerName",
                                  hintId = "paletteScaleQuantizerHint",
                                  portsId = "paletteScaleQuantizerPorts",
                                  layoutChild = { order = 5, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 }
                                },
                                paletteCard {
                                  id = "paletteNoteFilterCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff22c55e,
                                  name = "NOTE FILTER",
                                  hint = "",
                                  ports = "VOICE  ->  VOICE",
                                  deleteStubId = "paletteNoteFilterDeleteStub",
                                  accentId = "paletteNoteFilterAccent",
                                  resizeStubId = "paletteNoteFilterResizeStub",
                                  nameId = "paletteNoteFilterName",
                                  hintId = "paletteNoteFilterHint",
                                  portsId = "paletteNoteFilterPorts",
                                  layoutChild = { order = 5, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteRackOscillatorCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff7dd3fc,
                                  name = "OSC",
                                  hint = "",
                                  ports = "VOICE  ->  OUT",
                                  deleteStubId = "paletteRackOscillatorDeleteStub",
                                  accentId = "paletteRackOscillatorAccent",
                                  resizeStubId = "paletteRackOscillatorResizeStub",
                                  nameId = "paletteRackOscillatorName",
                                  hintId = "paletteRackOscillatorHint",
                                  portsId = "paletteRackOscillatorPorts",
                                  layoutChild = { order = 6, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteRackSampleCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff22d3ee,
                                  name = "SAMPLE",
                                  hint = "",
                                  ports = "IN/VOICE  ->  OUT",
                                  deleteStubId = "paletteRackSampleDeleteStub",
                                  accentId = "paletteRackSampleAccent",
                                  resizeStubId = "paletteRackSampleResizeStub",
                                  nameId = "paletteRackSampleName",
                                  hintId = "paletteRackSampleHint",
                                  portsId = "paletteRackSamplePorts",
                                  layoutChild = { order = 6, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteFilterCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xffa78bfa,
                                  name = "FILTER",
                                  hint = "",
                                  ports = "IN  ->  OUT",
                                  deleteStubId = "paletteFilterDeleteStub",
                                  accentId = "paletteFilterAccent",
                                  resizeStubId = "paletteFilterResizeStub",
                                  nameId = "paletteFilterName",
                                  hintId = "paletteFilterHint",
                                  portsId = "paletteFilterPorts",
                                  layoutChild = { order = 7, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteEqCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff34d399,
                                  name = "EQ",
                                  hint = "",
                                  ports = "IN  ->  OUT",
                                  deleteStubId = "paletteEqDeleteStub",
                                  accentId = "paletteEqAccent",
                                  resizeStubId = "paletteEqResizeStub",
                                  nameId = "paletteEqName",
                                  hintId = "paletteEqHint",
                                  portsId = "paletteEqPorts",
                                  layoutChild = { order = 8, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteFxCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xffa855f7,
                                  name = "FX",
                                  hint = "",
                                  ports = "IN  ->  OUT",
                                  deleteStubId = "paletteFxDeleteStub",
                                  accentId = "paletteFxAccent",
                                  resizeStubId = "paletteFxResizeStub",
                                  nameId = "paletteFxName",
                                  hintId = "paletteFxHint",
                                  portsId = "paletteFxPorts",
                                  layoutChild = { order = 9, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteAttenuverterBiasCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff22d3ee,
                                  name = "ATV / BIAS",
                                  hint = "",
                                  ports = "IN  ->  OUT",
                                  deleteStubId = "paletteAttenuverterBiasDeleteStub",
                                  accentId = "paletteAttenuverterBiasAccent",
                                  resizeStubId = "paletteAttenuverterBiasResizeStub",
                                  nameId = "paletteAttenuverterBiasName",
                                  hintId = "paletteAttenuverterBiasHint",
                                  portsId = "paletteAttenuverterBiasPorts",
                                  layoutChild = { order = 9, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteLfoCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff38bdf8,
                                  name = "LFO",
                                  hint = "",
                                  ports = "RST/SYNC  ->  OUT",
                                  deleteStubId = "paletteLfoDeleteStub",
                                  accentId = "paletteLfoAccent",
                                  resizeStubId = "paletteLfoResizeStub",
                                  nameId = "paletteLfoName",
                                  hintId = "paletteLfoHint",
                                  portsId = "paletteLfoPorts",
                                  layoutChild = { order = 10, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteSlewCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xff22d3ee,
                                  name = "SLEW",
                                  hint = "",
                                  ports = "IN  ->  OUT",
                                  deleteStubId = "paletteSlewDeleteStub",
                                  accentId = "paletteSlewAccent",
                                  resizeStubId = "paletteSlewResizeStub",
                                  nameId = "paletteSlewName",
                                  hintId = "paletteSlewHint",
                                  portsId = "paletteSlewPorts",
                                  layoutChild = { order = 10, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteSampleHoldCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xfff59e0b,
                                  name = "SAMPLE HOLD",
                                  hint = "",
                                  ports = "IN/TRIG  ->  OUT",
                                  deleteStubId = "paletteSampleHoldDeleteStub",
                                  accentId = "paletteSampleHoldAccent",
                                  resizeStubId = "paletteSampleHoldResizeStub",
                                  nameId = "paletteSampleHoldName",
                                  hintId = "paletteSampleHoldHint",
                                  portsId = "paletteSampleHoldPorts",
                                  layoutChild = { order = 10, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteCompareCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xfff97316,
                                  name = "COMPARE",
                                  hint = "",
                                  ports = "IN  ->  GATE/TRIG",
                                  deleteStubId = "paletteCompareDeleteStub",
                                  accentId = "paletteCompareAccent",
                                  resizeStubId = "paletteCompareResizeStub",
                                  nameId = "paletteCompareName",
                                  hintId = "paletteCompareHint",
                                  portsId = "paletteComparePorts",
                                  layoutChild = { order = 10, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteCvMixCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xffa855f7,
                                  name = "CV MIX",
                                  hint = "",
                                  ports = "IN1..4  ->  OUT",
                                  deleteStubId = "paletteCvMixDeleteStub",
                                  accentId = "paletteCvMixAccent",
                                  resizeStubId = "paletteCvMixResizeStub",
                                  nameId = "paletteCvMixName",
                                  hintId = "paletteCvMixHint",
                                  portsId = "paletteCvMixPorts",
                                  layoutChild = { order = 10, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                                paletteCard {
                                  id = "paletteRangeMapperCard",
                                  width = 102,
                                  height = 56,
                                  accentColor = 0xffa855f7,
                                  name = "RANGE",
                                  hint = "",
                                  ports = "IN  ->  OUT",
                                  deleteStubId = "paletteRangeMapperDeleteStub",
                                  accentId = "paletteRangeMapperAccent",
                                  resizeStubId = "paletteRangeMapperResizeStub",
                                  nameId = "paletteRangeMapperName",
                                  hintId = "paletteRangeMapperHint",
                                  portsId = "paletteRangeMapperPorts",
                                  layoutChild = { order = 9, grow = 0, shrink = 0, basisW = 102, minW = 102, maxW = 102, basisH = 56, minH = 56, maxH = 56 },
                                },
                              },
                            },
                          },
                        },
                      },
                    },
                    {
                      id = "utilityDetailPanel",
                      type = "Panel",
                      x = 0, y = 0, w = 164, h = 136,
                      layoutChild = { basisW = 164, minW = 164, grow = 1, shrink = 1 },
                      style = { bg = 0x00000000, border = 0x00000000, borderWidth = 0, radius = 0 },
                      props = { interceptsMouse = false },
                      layout = {
                        mode = "stack-y",
                        padding = { 0, 0, 0, 0 },
                        gap = 0,
                        align = "stretch",
                      },
                      children = {
                        {
                          id = "utilityDetailBody",
                          type = "Panel",
                          x = 0, y = 0, w = 164, h = 136,
                          layoutChild = { grow = 1, shrink = 1 },
                          style = { bg = 0x00000000 },
                          props = { interceptsMouse = false },
                          layout = {
                            mode = "stack-y",
                            padding = { 10, 10, 10, 10 },
                            gap = 6,
                            align = "stretch",
                          },
                          children = {
                            {
                              id = "utilityDetailTitle",
                              type = "Label",
                              x = 0, y = 0, w = 144, h = 18,
                              layoutChild = { basisH = 18, shrink = 0 },
                              props = { text = "ADSR" },
                              style = { colour = 0xffe2e8f0, fontSize = 13, fontWeight = "bold" },
                            },
                            {
                              id = "utilityDetailSubtitle",
                              type = "Label",
                              x = 0, y = 0, w = 144, h = 48,
                              layoutChild = { basisH = 48, shrink = 1 },
                              props = { text = "Canonical voice control module.", wordWrap = true },
                              style = { colour = 0xff94a3b8, fontSize = 10 },
                            },
                            {
                              id = "utilityDetailPorts",
                              type = "Label",
                              x = 0, y = 0, w = 144, h = 14,
                              layoutChild = { basisH = 14, shrink = 0 },
                              props = { text = "MIDI/VOICE -> VOICE, ENV, INV, EOC" },
                              style = { colour = 0xff64748b, fontSize = 9 },
                            },
                            {
                              id = "utilityDetailStatus",
                              type = "Label",
                              x = 0, y = 0, w = 144, h = 14,
                              layoutChild = { basisH = 14, shrink = 0 },
                              props = { text = "" },
                              style = { colour = 0xff38bdf8, fontSize = 9 },
                            },
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
            {
              id = "keyboardGrabHandle",
              type = "Panel",
              x = 0, y = 0, w = 1216, h = 8,
              layoutChild = { order = 2, grow = 0, shrink = 0, basisH = 8, minH = 8, maxH = 8 },
              style = { bg = 0x00000000 },
              props = { interceptsMouse = true },
              children = {
                {
                  id = "keyboardGrabHandleGrip",
                  type = "Panel",
                  x = 0, y = 0, w = 48, h = 2,
                  layout = { mode = "hybrid", left = 584, top = 3, width = 48, height = 2 },
                  style = { bg = 0xff475569, radius = 1 },
                  props = { interceptsMouse = false },
                },
              },
            },
            {
              id = "midiParamRack",
              type = "Panel",
              x = 0, y = 0, w = 1216, h = 68,
              layoutChild = { order = 3, grow = 0, shrink = 0, basisH = 68, minH = 68, maxH = 68 },
              style = { bg = 0xff0d1420, border = 0xff1f2937, borderWidth = 1, radius = 4 },
              props = { interceptsMouse = false },
            },
            {
              id = "keyboardBody",
              type = "Panel",
              x = 0, y = 0, w = 1216, h = 120,
              layoutChild = { order = 4, grow = 0, shrink = 1, basisH = 120, minH = 0 },
              style = { bg = 0x00000000 },
              props = { interceptsMouse = false },
              layout = {
                mode = "stack-y",
                padding = { 0, 0, 0, 0 },
                gap = 6,
                align = "stretch",
              },
              children = {
                {
                  id = "keyboardStatusSecondary",
                  type = "Label",
                  x = 0, y = 0, w = 1216, h = 14,
                  layoutChild = { basisH = 14, shrink = 0, alignSelf = "stretch" },
                  props = { text = "" },
                  style = { colour = 0xff94a3b8, fontSize = 10 },
                },
                {
                  id = "keyboardCanvas",
                  type = "Panel",
                  x = 0, y = 0, w = 1216, h = 100,
                  layoutChild = { grow = 1, shrink = 1, basisH = 100, minH = 40 },
                  style = { bg = 0xff0d1420, radius = 6 },
                },
              },
            },
            {
              id = "keyboardHeader",
              type = "Panel",
              x = 0, y = 0, w = 1216, h = 42,
              layoutChild = { order = 9, grow = 0, shrink = 0, basisH = 42, minH = 42, maxH = 42 },
              style = { bg = 0x00000000 },
              props = { interceptsMouse = false },
              layout = {
                mode = "stack-x",
                gap = 12,
                align = "center",
              },
              children = {
                {
                  id = "octaveCluster",
                  type = "Panel",
                  x = 0, y = 0, w = 260, h = 28,
                  layoutChild = { basisW = 260, shrink = 0, alignSelf = "center" },
                  style = { bg = 0x00000000 },
                  props = { interceptsMouse = false },
                  layout = {
                    mode = "stack-x",
                    gap = 6,
                    align = "center",
                  },
                  children = {
                    { id = "octaveDown", type = "Button", x = 0, y = 0, w = 48, h = 28, layoutChild = { basisW = 48, shrink = 0 }, props = { label = "Oct -" }, style = { bg = 0xff1e293b, border = 0xff38bdf8, borderWidth = 1, radius = 0, fontSize = 10 } },
                    { id = "octaveUp", type = "Button", x = 0, y = 0, w = 48, h = 28, layoutChild = { basisW = 48, shrink = 0 }, props = { label = "Oct +" }, style = { bg = 0xff1e293b, border = 0xff38bdf8, borderWidth = 1, radius = 0, fontSize = 10 } },
                    { id = "octaveLabel", type = "Label", x = 0, y = 0, w = 72, h = 16, layoutChild = { basisW = 72, shrink = 0, alignSelf = "center" }, props = { text = "C3-C5" }, style = { colour = 0xffcbd5e1, fontSize = 11 } },
                    { id = "keyCountButton", type = "Button", x = 0, y = 0, w = 36, h = 28, layoutChild = { basisW = 36, shrink = 0 }, props = { label = "14k" }, style = { bg = 0xff1e293b, border = 0xff38bdf8, borderWidth = 1, radius = 0, fontSize = 9 } },
                  },
                },
                {
                  id = "statusCluster",
                  type = "Panel",
                  x = 0, y = 0, w = 420, h = 28,
                  layoutChild = { grow = 1, shrink = 1, basisW = 420, minW = 260, alignSelf = "center" },
                  style = { bg = 0x00000000 },
                  props = { interceptsMouse = false },
                  layout = {
                    mode = "stack-x",
                    gap = 4,
                    align = "center",
                  },
                  children = {
                    { id = "keyboardStatusPrimary", type = "Label", x = 0, y = 0, w = 220, h = 16, layoutChild = { grow = 1, shrink = 1, basisW = 220, minW = 180, alignSelf = "center" }, props = { text = "" }, style = { colour = 0xffcbd5e1, fontSize = 11 } },
                    { id = "voiceNote1", type = "Label", x = 0, y = 0, w = 36, h = 18, layoutChild = { basisW = 36, shrink = 0, alignSelf = "center" }, props = { text = "" }, style = { colour = 0xff4ade80, fontSize = 12 } },
                    { id = "voiceNote2", type = "Label", x = 0, y = 0, w = 36, h = 18, layoutChild = { basisW = 36, shrink = 0, alignSelf = "center" }, props = { text = "" }, style = { colour = 0xff38bdf8, fontSize = 12 } },
                    { id = "voiceNote3", type = "Label", x = 0, y = 0, w = 36, h = 18, layoutChild = { basisW = 36, shrink = 0, alignSelf = "center" }, props = { text = "" }, style = { colour = 0xfffbbf24, fontSize = 12 } },
                    { id = "voiceNote4", type = "Label", x = 0, y = 0, w = 36, h = 18, layoutChild = { basisW = 36, shrink = 0, alignSelf = "center" }, props = { text = "" }, style = { colour = 0xfff87171, fontSize = 12 } },
                    { id = "voiceNote5", type = "Label", x = 0, y = 0, w = 36, h = 18, layoutChild = { basisW = 36, shrink = 0, alignSelf = "center" }, props = { text = "" }, style = { colour = 0xffa78bfa, fontSize = 12 } },
                    { id = "voiceNote6", type = "Label", x = 0, y = 0, w = 36, h = 18, layoutChild = { basisW = 36, shrink = 0, alignSelf = "center" }, props = { text = "" }, style = { colour = 0xff2dd4bf, fontSize = 12 } },
                    { id = "voiceNote7", type = "Label", x = 0, y = 0, w = 36, h = 18, layoutChild = { basisW = 36, shrink = 0, alignSelf = "center" }, props = { text = "" }, style = { colour = 0xfffb923c, fontSize = 12 } },
                    { id = "voiceNote8", type = "Label", x = 0, y = 0, w = 36, h = 18, layoutChild = { basisW = 36, shrink = 0, alignSelf = "center" }, props = { text = "" }, style = { colour = 0xfff472b6, fontSize = 12 } },
                  },
                },
                {
                  id = "midiCluster",
                  type = "Panel",
                  x = 0, y = 0, w = 372, h = 28,
                  layoutChild = { basisW = 372, shrink = 0, alignSelf = "center" },
                  style = { bg = 0x00000000 },
                  props = { interceptsMouse = false },
                  layout = {
                    mode = "stack-x",
                    gap = 8,
                    align = "center",
                  },
                  children = {
                    { id = "midiInputDropdown", type = "Dropdown", x = 0, y = 0, w = 180, h = 28, layoutChild = { grow = 1, shrink = 1, basisW = 180, minW = 140 }, props = { options = { "None (Disabled)" }, selected = 1, max_visible_rows = 8 }, style = { bg = 0xff1e293b, colour = 0xff38bdf8, radius = 0 } },
                    { id = "refreshMidi", type = "Button", x = 0, y = 0, w = 64, h = 28, layoutChild = { basisW = 64, shrink = 0 }, props = { label = "Refresh" }, style = { bg = 0xff1e293b, border = 0xff38bdf8, borderWidth = 1, radius = 0, fontSize = 10 } },
                    { id = "panic", type = "Button", x = 0, y = 0, w = 64, h = 28, layoutChild = { basisW = 64, shrink = 0 }, props = { label = "Panic" }, style = { bg = 0xff1e293b, border = 0xfff87171, borderWidth = 1, radius = 0, fontSize = 11 } },
                  },
                },
              },
            },
            PaginationDots({
              id = "dockModeDots",
              dotIds = { "dockModeDotFull", "dockModeDotCompactSplit", "dockModeDotCompactCollapsed" },
              count = 3,
              orientation = "y",
              gap = 5,
              layoutChild = { position = "absolute" },
            }),
          },
        },
      },
      components = {},
    },
  },
}
