return {
  id = "placeholderKnobContent",
  type = "Panel",
  x = 0,
  y = 0,
  w = 236,
  h = 220,
  layout = { mode = "hybrid", left = 0, top = 0, right = 0, bottom = 0 },
  style = {
    bg = 0x00000000,
  },
  props = { interceptsMouse = false },
  children = {
    {
      id = "placeholderBadge",
      type = "Label",
      x = 18,
      y = 18,
      w = 180,
      h = 18,
      props = { text = "Placeholder + Knob" },
      style = { colour = 0xff94a3b8, fontSize = 13 },
    },
    {
      id = "placeholderHint",
      type = "Label",
      x = 18,
      y = 40,
      w = 180,
      h = 16,
      props = { text = "Reload smoke test" },
      style = { colour = 0xff64748b, fontSize = 11 },
    },
    {
      id = "placeholderCard",
      type = "Panel",
      x = 18,
      y = 66,
      w = 200,
      h = 132,
      style = {
        bg = 0xff0f172a,
        border = 0xff334155,
        borderWidth = 1,
        radius = 8,
      },
      props = { interceptsMouse = false },
      children = {
        {
          id = "demoKnob",
          type = "Knob",
          x = 64,
          y = 18,
          w = 72,
          h = 88,
          props = {
            min = 0,
            max = 1,
            step = 0.01,
            value = 0.42,
            label = "TEST",
          },
          style = { colour = 0xfff59e0b },
        },
      },
    },
  },
}
