return {
  id = "rackOscillatorRoot",
  type = "Panel",
  x = 0, y = 0, w = 472, h = 208,
  style = { bg = 0xff121a2f, border = 0xff1f2b4d, borderWidth = 1, radius = 10 },
  ports = {
    inputs = {
      { id = "gate", type = "control", y = 0.20, label = "GATE" },
      { id = "v_oct", type = "control", y = 0.40, label = "V/OCT" },
      { id = "fm", type = "control", y = 0.60, label = "FM" },
      { id = "pw_cv", type = "control", y = 0.80, label = "PW" },
    },
    outputs = {
      { id = "out", type = "audio", y = 0.35, label = "OUT" },
      { id = "sub", type = "audio", y = 0.70, label = "SUB" },
      { id = "analysis", type = "analysis", y = 0.88, label = "AN" },
    },
  },
  children = {
    { id = "title", type = "Label", x = 16, y = 8, w = 200, h = 14, props = { text = "OSCILLATOR" }, style = { colour = 0xff7dd3fc, fontSize = 12 } },
    { id = "osc_graph", type = "Panel", x = 10, y = 10, w = 226, h = 132, style = { bg = 0xff0d1420, border = 0xff1a1a3a, borderWidth = 1, radius = 6 } },
    {
      id = "mode_tabs",
      type = "TabHost",
      x = 242, y = 10, w = 220, h = 188,
      props = {
        activeIndex = 1,
        tabBarHeight = 24,
        tabSizing = "fill",
      },
      style = {
        bg = 0xff0b1220,
        border = 0xff1f2937,
        borderWidth = 1,
        radius = 6,
        tabBarBg = 0xff0d1420,
        tabBg = 0xff1e293b,
        activeTabBg = 0xff2563eb,
        textColour = 0xff94a3b8,
        activeTextColour = 0xffffffff,
      },
      children = {
        {
          id = "wave_tab",
          type = "TabPage",
          x = 0, y = 24, w = 220, h = 164,
          props = { title = "Wave" },
          style = { bg = 0x00000000 },
          children = {
            { id = "waveform_dropdown", type = "Dropdown", x = 4, y = 4, w = 114, h = 20, props = { options = { "Sine", "Saw", "Square", "Triangle", "Blend", "Noise", "Pulse", "SuperSaw" }, selected = 2, max_visible_rows = 8 }, style = { bg = 0xff1e293b, colour = 0xff38bdf8, radius = 0 } },
            { id = "render_mode_tabs", type = "SegmentedControl", x = 126, y = 4, w = 84, h = 20, props = { segments = { "Std", "Add" }, selected = 1 }, style = { bg = 0xff1e293b, selectedBg = 0xff2563eb, textColour = 0xff94a3b8, selectedTextColour = 0xffffffff } },
            { id = "pulse_width_knob", type = "Slider", x = 10, y = 30, w = 200, h = 20, props = { min = 0.01, max = 0.99, step = 0.01, value = 0.5, label = "Width", compact = true, showValue = true }, style = { colour = 0xffa78bfa, bg = 0xff1e1b33, fontSize = 9 } },
            { id = "add_partials_knob", type = "Slider", x = 10, y = 30, w = 200, h = 20, props = { min = 1, max = 12, step = 1, value = 8, label = "Parts", compact = true, showValue = true }, style = { colour = 0xff22d3ee, bg = 0xff08212a, fontSize = 9 } },
            { id = "add_tilt_knob", type = "Slider", x = 10, y = 56, w = 97, h = 20, props = { min = -1, max = 1, step = 0.01, value = 0.0, label = "Tilt", compact = true, bidirectional = true, showValue = true }, style = { colour = 0xfffbbf24, bg = 0xff2b2008, fontSize = 9 } },
            { id = "add_drift_knob", type = "Slider", x = 113, y = 56, w = 97, h = 20, props = { min = 0, max = 1, step = 0.01, value = 0.0, label = "Drift", compact = true, showValue = true }, style = { colour = 0xff34d399, bg = 0xff10231d, fontSize = 9 } },
            { id = "drive_curve", type = "CurveWidget", x = 10, y = 82, w = 56, h = 56, props = { title = "DRV", editable = false }, style = { colour = 0xfff97316, bg = 0xff120d0a, gridColour = 0xff2a1a12, axisColour = 0xff4b2d1d } },
            { id = "drive_mode_dropdown", type = "Dropdown", x = 74, y = 82, w = 62, h = 20, props = { options = { "Soft", "Hard", "Clip", "Fold" }, selected = 1, max_visible_rows = 4 }, style = { bg = 0xff1e293b, colour = 0xfff97316, fontSize = 9, radius = 0 } },
            { id = "drive_knob", type = "Slider", x = 74, y = 108, w = 62, h = 20, props = { min = 0, max = 20, step = 0.1, value = 0.0, label = "Drive", compact = true, showValue = true }, style = { colour = 0xfff97316, bg = 0xff2a1208, fontSize = 9 } },
            { id = "drive_bias_knob", type = "Slider", x = 74, y = 134, w = 62, h = 20, props = { min = -1, max = 1, step = 0.01, value = 0.0, label = "Bias", compact = true, bidirectional = true, showValue = true }, style = { colour = 0xfffb7185, bg = 0xff2a1117, fontSize = 9 } },
          },
        },
      },
    },
    { id = "unison_knob", type = "Slider", x = 16, y = 150, w = 66, h = 20, props = { min = 1, max = 8, step = 1, value = 1, label = "Unison", compact = true, showValue = true }, style = { colour = 0xff22d3ee, bg = 0xff08212a, fontSize = 9 } },
    { id = "detune_knob", type = "Slider", x = 90, y = 150, w = 66, h = 20, props = { min = 0, max = 100, step = 1, value = 0, label = "Detune", compact = true, showValue = true }, style = { colour = 0xff4ade80, bg = 0xff102317, fontSize = 9 } },
    { id = "spread_knob", type = "Slider", x = 164, y = 150, w = 66, h = 20, props = { min = 0, max = 1, step = 0.01, value = 0, label = "Spread", compact = true, showValue = true }, style = { colour = 0xfffbbf24, bg = 0xff2b2008, fontSize = 9 } },
    { id = "manual_pitch_knob", type = "Slider", x = 10, y = 176, w = 70, h = 22, props = { min = 0, max = 127, step = 1, value = 60, label = "Pitch", compact = true, showValue = true }, style = { colour = 0xff60a5fa, bg = 0xff0f1b2f, fontSize = 9 } },
    { id = "manual_level_knob", type = "Slider", x = 88, y = 176, w = 70, h = 22, props = { min = 0, max = 1, step = 0.01, value = 0.0, label = "Level", compact = true, showValue = true }, style = { colour = 0xfff59e0b, bg = 0xff2a1b08, fontSize = 9 } },
    { id = "output_knob", type = "Slider", x = 166, y = 176, w = 70, h = 22, props = { min = 0, max = 2, step = 0.01, value = 0.8, label = "Output", compact = true, showValue = true }, style = { colour = 0xff34d399, bg = 0xff10231d, fontSize = 9 } },
  },
}
