return {
  id = "transport_root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 44,
  style = {
    bg = 4279507492,
    radius = 0,
  },
  children = {
    {
      id = "mode",
      type = "Dropdown",
      x = 6,
      y = 11,
      w = 72,
      h = 26,
      props = {
        options = {
          "First Loop",
          "Free Mode",
          "Traditional",
        },
        selected = 1,
      },
      style = {
        bg = 4280240762,
        colour = 4286436348,
        radius = 0,
      },
    },
    {
      id = "rec",
      type = "Button",
      x = 84,
      y = 11,
      w = 56,
      h = 26,
      props = {
        label = "● REC",
      },
      style = {
        bg = 4286520605,
        fontSize = 11,
        border = 4286520605,
        borderWidth = 1,
        radius = 0,
      },
    },
    {
      id = "playpause",
      type = "Button",
      x = 146,
      y = 11,
      w = 58,
      h = 26,
      props = {
        label = "▶ PLAY",
      },
      style = {
        bg = 4280252986,
        fontSize = 11,
        border = 4286436348,
        borderWidth = 1,
        radius = 0,
      },
    },
    {
      id = "stop",
      type = "Button",
      x = 210,
      y = 11,
      w = 58,
      h = 26,
      props = {
        label = "⏹ STOP",
      },
      style = {
        bg = 4281811281,
        fontSize = 11,
        border = 4283127139,
        borderWidth = 1,
        radius = 0,
      },
    },
    {
      id = "overdub",
      type = "Toggle",
      x = 274,
      y = 11,
      w = 56,
      h = 26,
      props = {
        label = "Overdub",
        value = true,
      },
      style = {
        offColour = 4281811281,
        onColour = 4294286859,
        radius = 0,
      },
    },
    {
      id = "clearall",
      type = "Button",
      x = 336,
      y = 11,
      w = 48,
      h = 26,
      props = {
        label = "Clear",
      },
      style = {
        bg = 4280232247,
        fontSize = 10,
        border = 4289296557,
        borderWidth = 1,
        radius = 0,
      },
    },
    {
      id = "linkIndicator",
      type = "Label",
      x = 1020,
      y = 11,
      w = 50,
      h = 26,
      props = {
        text = "link",
      },
      style = {
        colour = 4283127139,
        fontSize = 11,
      },
    },
    {
      id = "tempo",
      type = "NumberBox",
      x = 1076,
      y = 9,
      w = 96,
      h = 26,
      props = {
        format = "%d",
        label = "BPM",
        max = 240,
        min = 40,
        step = 1,
        value = 120,
      },
      style = {
        colour = 4281908728,
      },
    },
    {
      id = "targetBpm",
      type = "NumberBox",
      x = 1178,
      y = 9,
      w = 96,
      h = 26,
      props = {
        format = "%d",
        label = "Target",
        max = 240,
        min = 40,
        step = 1,
        value = 120,
      },
      style = {
        colour = 4280472558,
      },
    },
  },
}
