return {
  id = "capture_root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 130,
  style = {
    bg = 4279244579,
    radius = 8,
  },
  children = {
    {
      id = "captureTitle",
      type = "Label",
      x = 0,
      y = 0,
      w = 0,
      h = 0,
      props = {
        text = "",
      },
      style = {
        colour = 4288455599,
        fontSize = 12,
      },
    },
    {
      id = "strip_1",
      type = "Panel",
      x = 0,
      y = 4,
      w = 142,
      h = 122,
      props = {
        bars = 16.0,
        label = "16",
      },
      style = {
        bg = 4279180077,
        interceptsMouse = false,
      },
    },
    {
      id = "strip_2",
      type = "Panel",
      x = 142,
      y = 4,
      w = 142,
      h = 122,
      props = {
        bars = 8.0,
        label = "8",
      },
      style = {
        bg = 4279180077,
        interceptsMouse = false,
      },
    },
    {
      id = "strip_3",
      type = "Panel",
      x = 284,
      y = 4,
      w = 142,
      h = 122,
      props = {
        bars = 4.0,
        label = "4",
      },
      style = {
        bg = 4279180077,
        interceptsMouse = false,
      },
    },
    {
      id = "strip_4",
      type = "Panel",
      x = 426,
      y = 4,
      w = 142,
      h = 122,
      props = {
        bars = 2.0,
        label = "2",
      },
      style = {
        bg = 4279180077,
        interceptsMouse = false,
      },
    },
    {
      id = "strip_5",
      type = "Panel",
      x = 568,
      y = 4,
      w = 142,
      h = 122,
      props = {
        bars = 1.0,
        label = "1",
      },
      style = {
        bg = 4279180077,
        interceptsMouse = false,
      },
    },
    {
      id = "strip_6",
      type = "Panel",
      x = 710,
      y = 4,
      w = 142,
      h = 122,
      props = {
        bars = 0.5,
        label = "1/2",
      },
      style = {
        bg = 4279180077,
        interceptsMouse = false,
      },
    },
    {
      id = "strip_7",
      type = "Panel",
      x = 852,
      y = 4,
      w = 142,
      h = 122,
      props = {
        bars = 0.25,
        label = "1/4",
      },
      style = {
        bg = 4279180077,
        interceptsMouse = false,
      },
    },
    {
      id = "strip_8",
      type = "Panel",
      x = 994,
      y = 4,
      w = 142,
      h = 122,
      props = {
        bars = 0.125,
        label = "1/8",
      },
      style = {
        bg = 4279180077,
        interceptsMouse = false,
      },
    },
    {
      id = "strip_9",
      type = "Panel",
      x = 1136,
      y = 4,
      w = 142,
      h = 122,
      props = {
        bars = 0.0625,
        label = "1/16",
      },
      style = {
        bg = 4279180077,
        interceptsMouse = false,
      },
    },
    {
      id = "segment_hit_9",
      type = "Panel",
      x = 0,
      y = 4,
      w = 1278,
      h = 122,
      props = {
        bars = 16.0,
        label = "16",
      },
      style = {
        bg = 0,
        interceptsMouse = true,
      },
    },
    {
      id = "segment_hit_8",
      type = "Panel",
      x = 142,
      y = 4,
      w = 1136,
      h = 122,
      props = {
        bars = 8.0,
        label = "8",
      },
      style = {
        bg = 0,
        interceptsMouse = true,
      },
    },
    {
      id = "segment_hit_7",
      type = "Panel",
      x = 284,
      y = 4,
      w = 994,
      h = 122,
      props = {
        bars = 4.0,
        label = "4",
      },
      style = {
        bg = 0,
        interceptsMouse = true,
      },
    },
    {
      id = "segment_hit_6",
      type = "Panel",
      x = 426,
      y = 4,
      w = 852,
      h = 122,
      props = {
        bars = 2.0,
        label = "2",
      },
      style = {
        bg = 0,
        interceptsMouse = true,
      },
    },
    {
      id = "segment_hit_5",
      type = "Panel",
      x = 568,
      y = 4,
      w = 710,
      h = 122,
      props = {
        bars = 1.0,
        label = "1",
      },
      style = {
        bg = 0,
        interceptsMouse = true,
      },
    },
    {
      id = "segment_hit_4",
      type = "Panel",
      x = 710,
      y = 4,
      w = 568,
      h = 122,
      props = {
        bars = 0.5,
        label = "1/2",
      },
      style = {
        bg = 0,
        interceptsMouse = true,
      },
    },
    {
      id = "segment_hit_3",
      type = "Panel",
      x = 852,
      y = 4,
      w = 426,
      h = 122,
      props = {
        bars = 0.25,
        label = "1/4",
      },
      style = {
        bg = 0,
        interceptsMouse = true,
      },
    },
    {
      id = "segment_hit_2",
      type = "Panel",
      x = 994,
      y = 4,
      w = 284,
      h = 122,
      props = {
        bars = 0.125,
        label = "1/8",
      },
      style = {
        bg = 0,
        interceptsMouse = true,
      },
    },
    {
      id = "segment_hit_1",
      type = "Panel",
      x = 1136,
      y = 4,
      w = 142,
      h = 122,
      props = {
        bars = 0.0625,
        label = "1/16",
      },
      style = {
        bg = 0,
        interceptsMouse = true,
      },
    },
  },
}
