return {
  id = "root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 720,
  style = {
    bg = 0xff060b16,
  },
  behavior = "ui/behaviors/donut_view.lua",
  children = {},
  components = {
    {
      id = "transport",
      x = 8,
      y = 8,
      w = 1264,
      h = 62,
      behavior = "ui/behaviors/donut_transport.lua",
      ref = "ui/components/donut_transport.ui.lua",
    },
    {
      id = "capture_plane",
      x = 8,
      y = 78,
      w = 1264,
      h = 96,
      behavior = "ui/behaviors/donut_capture_plane.lua",
      ref = "ui/components/donut_capture_plane.ui.lua",
    },
    {
      id = "vocal_fx",
      x = 8,
      y = 182,
      w = 1264,
      h = 170,
      behavior = "ui/behaviors/donut_vocal_fx.lua",
      ref = "ui/components/donut_vocal_fx.ui.lua",
    },
    {
      id = "layer0",
      x = 8,
      y = 360,
      w = 628,
      h = 172,
      props = { layerIndex = 0 },
      behavior = "ui/behaviors/donut_layer_card.lua",
      ref = "ui/components/donut_layer_card.ui.lua",
    },
    {
      id = "layer1",
      x = 644,
      y = 360,
      w = 628,
      h = 172,
      props = { layerIndex = 1 },
      behavior = "ui/behaviors/donut_layer_card.lua",
      ref = "ui/components/donut_layer_card.ui.lua",
    },
    {
      id = "layer2",
      x = 8,
      y = 540,
      w = 628,
      h = 172,
      props = { layerIndex = 2 },
      behavior = "ui/behaviors/donut_layer_card.lua",
      ref = "ui/components/donut_layer_card.ui.lua",
    },
    {
      id = "layer3",
      x = 644,
      y = 540,
      w = 628,
      h = 172,
      props = { layerIndex = 3 },
      behavior = "ui/behaviors/donut_layer_card.lua",
      ref = "ui/components/donut_layer_card.ui.lua",
    },
  },
}
