local RackLayout = require("behaviors.rack_layout")

local M = {}

local function copyPorts(ports)
  local out = { inputs = {}, outputs = {}, params = {} }
  if type(ports) ~= "table" then
    return out
  end
  for _, key in ipairs({ "inputs", "outputs", "params" }) do
    local source = type(ports[key]) == "table" and ports[key] or {}
    for i = 1, #source do
      out[key][i] = source[i]
    end
  end
  return out
end

local NODE_SPECS = {
  RackLayout.makeNodeSpec {
    id = "adsr",
    name = "ADSR",
    validSizes = { "1x1", "1x2", "2x1" },
    accentColor = 0xfffda4af,
    ports = copyPorts {
      inputs = {
        { id = "gate", type = "control", label = "GATE" },
        { id = "retrig", type = "control", label = "RETRIG" },
      },
      outputs = {
        { id = "env", type = "control", label = "ENV" },
        { id = "inv", type = "control", label = "INV" },
        { id = "eoc", type = "control", label = "EOC" },
      },
      params = {
        { id = "attack", label = "Attack", path = "/midi/synth/adsr/attack",
          min = 0.001, max = 2.0, step = 0.001, default = 0.05,
          format = "time", input = true, output = true },
        { id = "decay", label = "Decay", path = "/midi/synth/adsr/decay",
          min = 0.001, max = 2.0, step = 0.001, default = 0.2,
          format = "time", input = true, output = true },
        { id = "sustain", label = "Sustain", path = "/midi/synth/adsr/sustain",
          min = 0.0, max = 1.0, step = 0.01, default = 0.7,
          format = "percent", input = true, output = true },
        { id = "release", label = "Release", path = "/midi/synth/adsr/release",
          min = 0.001, max = 5.0, step = 0.001, default = 0.4,
          format = "time", input = true, output = true },
      },
    },
    meta = {
      componentId = "envelopeComponent",
      behavior = "ui/behaviors/envelope.lua",
      componentRef = "ui/components/envelope.ui.lua",
    },
  },
  RackLayout.makeNodeSpec {
    id = "oscillator",
    name = "Oscillator",
    validSizes = { "1x2", "2x1", "2x2" },
    accentColor = 0xff7dd3fc,
    ports = copyPorts {
      inputs = {
        { id = "gate", type = "control", label = "GATE" },
        { id = "v_oct", type = "control", label = "V/OCT" },
        { id = "fm", type = "control", label = "FM" },
        { id = "pw_cv", type = "control", label = "PW" },
        { id = "blend_cv", type = "control", label = "BLEND" },
      },
      outputs = {
        { id = "out", type = "audio", label = "OUT" },
        { id = "sub", type = "audio", label = "SUB" },
      },
      params = {
        { id = "waveform", label = "Wave", path = "/midi/synth/waveform",
          min = 0, max = 7, step = 1, default = 1,
          format = "enum",
          options = { "Sine", "Saw", "Sqr", "Tri", "Blend", "Noise", "Pulse", "SSaw" },
          input = true, output = true },
        { id = "render_mode", label = "Render", path = "/midi/synth/osc/renderMode",
          min = 0, max = 1, step = 1, default = 0,
          format = "enum",
          options = { "Std", "Add" },
          input = true, output = true },
        { id = "add_partials", label = "Parts", path = "/midi/synth/osc/add/partials",
          min = 1, max = 32, step = 1, default = 8,
          format = "int", input = true, output = true },
        { id = "add_tilt", label = "Tilt", path = "/midi/synth/osc/add/tilt",
          min = -1, max = 1, step = 0.01, default = 0,
          input = true, output = true },
        { id = "add_drift", label = "Drift", path = "/midi/synth/osc/add/drift",
          min = 0, max = 1, step = 0.01, default = 0,
          input = true, output = true },
        { id = "drive", label = "Drive", path = "/midi/synth/drive",
          min = 0, max = 20, step = 0.1, default = 0.0,
          input = true, output = true },
        { id = "drive_shape", label = "Shape", path = "/midi/synth/driveShape",
          min = 0, max = 3, step = 1, default = 0,
          format = "enum",
          options = { "Soft", "Hard", "Clip", "Fold" },
          input = true, output = true },
        { id = "drive_bias", label = "Bias", path = "/midi/synth/driveBias",
          min = -1, max = 1, step = 0.01, default = 0,
          input = true, output = true },
        { id = "pulse_width", label = "Width", path = "/midi/synth/pulseWidth",
          min = 0.01, max = 0.99, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "unison", label = "Unison", path = "/midi/synth/unison",
          min = 1, max = 8, step = 1, default = 1,
          format = "int", input = true, output = true },
        { id = "detune", label = "Detune", path = "/midi/synth/detune",
          min = 0, max = 100, step = 1, default = 0,
          format = "int", input = true, output = true },
        { id = "spread", label = "Spread", path = "/midi/synth/spread",
          min = 0, max = 1, step = 0.01, default = 0,
          input = true, output = true },
        { id = "blend_amount", label = "Blend", path = "/midi/synth/blend/amount",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "output", label = "Output", path = "/midi/synth/output",
          min = 0, max = 1, step = 0.01, default = 0.8,
          input = true, output = true },
        -- Sample tab params
        { id = "sample_source", label = "Source", path = "/midi/synth/sample/source",
          min = 0, max = 4, step = 1, default = 0,
          format = "enum",
          options = { "Live", "Layer 1", "Layer 2", "Layer 3", "Layer 4" },
          input = true, output = true },
        { id = "sample_bars", label = "Bars", path = "/midi/synth/sample/captureBars",
          min = 0.0625, max = 16, step = 0.0625, default = 1,
          input = true, output = true },
        { id = "sample_root", label = "Root", path = "/midi/synth/sample/rootNote",
          min = 12, max = 96, step = 1, default = 60,
          format = "int", input = true, output = true },
        { id = "sample_pitch_map", label = "PMap", path = "/midi/synth/sample/pitchMapEnabled",
          min = 0, max = 1, step = 1, default = 0,
          format = "enum",
          options = { "Off", "On" },
          input = true, output = true },
        { id = "sample_start", label = "Start", path = "/midi/synth/sample/loopStart",
          min = 0, max = 95, step = 1, default = 0,
          format = "int", input = true, output = true,
          scale = { dspMin = 0.0, dspMax = 0.95 } },
        { id = "sample_play_start", label = "Play", path = "/midi/synth/sample/playStart",
          min = 0, max = 99, step = 1, default = 0,
          format = "int", input = true, output = true,
          scale = { dspMin = 0.0, dspMax = 0.99 } },
        { id = "sample_len", label = "Length", path = "/midi/synth/sample/loopLen",
          min = 5, max = 100, step = 1, default = 100,
          format = "int", input = true, output = true,
          scale = { dspMin = 0.05, dspMax = 1.0 } },
        { id = "sample_xfade", label = "X-Fade", path = "/midi/synth/sample/crossfade",
          min = 0, max = 50, step = 1, default = 10,
          format = "int", input = true, output = true,
          scale = { dspMin = 0.0, dspMax = 0.5 } },
        { id = "sample_retrigger", label = "Retrig", path = "/midi/synth/sample/retrigger",
          min = 0, max = 1, step = 1, default = 1,
          format = "enum",
          options = { "Off", "On" },
          input = true, output = true },
        { id = "sample_capture", label = "Capture", path = "/midi/synth/sample/captureTrigger",
          min = 0, max = 1, step = 1, default = 0,
          format = "enum",
          options = { "Idle", "Trig" },
          input = true, output = false },
        -- Blend tab params
        { id = "blend_mode", label = "Mode", path = "/midi/synth/blend/mode",
          min = 0, max = 5, step = 1, default = 0,
          format = "enum",
          options = { "Mix", "Ring", "FM", "Sync", "Add", "Morph" },
          input = true, output = true },
        { id = "blend_key_track", label = "KeyTrk", path = "/midi/synth/blend/keyTrack",
          min = 0, max = 2, step = 1, default = 2,
          format = "enum",
          options = { "Wave", "Sample", "Both" },
          input = true, output = true },
        { id = "blend_sample_pitch", label = "Pitch", path = "/midi/synth/blend/samplePitch",
          min = -24, max = 24, step = 1, default = 0,
          format = "int", input = true, output = true },
        { id = "blend_mod_amount", label = "Depth", path = "/midi/synth/blend/modAmount",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "blend_add_flavor", label = "AddSrc", path = "/midi/synth/blend/addFlavor",
          min = 0, max = 1, step = 1, default = 0,
          format = "enum",
          options = { "Self", "Driven" },
          input = true, output = true },
        { id = "morph_curve", label = "Curve", path = "/midi/synth/blend/morphCurve",
          min = 0, max = 2, step = 1, default = 2,
          format = "enum",
          options = { "Linear", "S-Curve", "EqPwr" },
          input = true, output = true },
        { id = "morph_convergence", label = "Stretch", path = "/midi/synth/blend/morphConvergence",
          min = 0, max = 1, step = 0.01, default = 0,
          format = "percent",
          input = true, output = true },
        { id = "morph_phase", label = "Tilt", path = "/midi/synth/blend/morphPhase",
          min = 0, max = 2, step = 1, default = 0,
          format = "enum",
          options = { "Neutral", "Bright", "Dark" },
          input = true, output = true },
        { id = "morph_speed", label = "Speed", path = "/midi/synth/blend/morphSpeed",
          min = 0.1, max = 4.0, step = 0.1, default = 1.0,
          format = "float",
          input = true, output = true },
        { id = "morph_contrast", label = "Contrast", path = "/midi/synth/blend/morphContrast",
          min = 0, max = 2, step = 0.01, default = 0.5,
          format = "float",
          input = true, output = true },
        { id = "morph_smooth", label = "Smooth", path = "/midi/synth/blend/morphSmooth",
          min = 0, max = 1, step = 0.01, default = 0.0,
          format = "percent",
          input = true, output = true },
      },
    },
    meta = {
      componentId = "oscillatorComponent",
      behavior = "ui/behaviors/oscillator.lua",
      componentRef = "ui/components/oscillator.ui.lua",
    },
  },
  RackLayout.makeNodeSpec {
    id = "filter",
    name = "Filter",
    validSizes = { "1x1", "1x2", "2x1", "2x2" },
    accentColor = 0xffa78bfa,
    ports = copyPorts {
      inputs = {
        { id = "in", type = "audio", label = "IN" },
        { id = "env", type = "control", label = "ENV" },
      },
      outputs = {
        { id = "out", type = "audio", label = "OUT" },
        { id = "send", type = "audio", label = "SEND", edge = "right" },
      },
      params = {
        { id = "type", label = "Type", path = "/midi/synth/filterType",
          min = 0, max = 3, step = 1, default = 0,
          format = "enum",
          options = { "SVF LP", "SVF BP", "SVF HP", "SVF Notch" },
          input = true, output = true },
        { id = "cutoff", label = "Cutoff", path = "/midi/synth/cutoff",
          min = 80, max = 16000, step = 1, default = 3200,
          format = "freq", input = true, output = true },
        { id = "resonance", label = "Reso", path = "/midi/synth/resonance",
          min = 0.1, max = 2.0, step = 0.01, default = 0.75,
          input = true, output = true },
      },
    },
    meta = {
      componentId = "filterComponent",
      behavior = "ui/behaviors/filter.lua",
      componentRef = "ui/components/filter.ui.lua",
    },
  },
  RackLayout.makeNodeSpec {
    id = "fx1",
    name = "FX1",
    validSizes = { "1x1", "1x2", "2x1", "2x2" },
    accentColor = 0xffa855f7,
    ports = copyPorts {
      inputs = {
        { id = "in", type = "audio", label = "IN" },
        { id = "recv", type = "audio", label = "RECV", edge = "left" },
      },
      outputs = {
        { id = "out", type = "audio", label = "OUT" },
      },
      params = {
        { id = "type", label = "Type", path = "/midi/synth/fx1/type",
          min = 0, max = 16, step = 1, default = 0,
          format = "enum",
          options = { "Chorus", "Phaser", "WvShp", "Comp", "Widen", "Filt", "SVF", "Verb", "SDly", "MTap", "Pitch", "Gran", "Ring", "Fmnt", "EQ", "Limit", "Trans" },
          input = true, output = true },
        { id = "mix", label = "Mix", path = "/midi/synth/fx1/mix",
          min = 0, max = 1, step = 0.01, default = 0,
          input = true, output = true },
        { id = "p0", label = "P1", path = "/midi/synth/fx1/p/0",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "p1", label = "P2", path = "/midi/synth/fx1/p/1",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "p2", label = "P3", path = "/midi/synth/fx1/p/2",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "p3", label = "P4", path = "/midi/synth/fx1/p/3",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "p4", label = "P5", path = "/midi/synth/fx1/p/4",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
      },
    },
    meta = {
      componentId = "fx1Component",
      behavior = "ui/behaviors/fx_slot.lua",
      componentRef = "ui/components/fx_slot.ui.lua",
      slot = 1,
    },
  },
  RackLayout.makeNodeSpec {
    id = "fx2",
    name = "FX2",
    validSizes = { "1x1", "1x2", "2x1" },
    accentColor = 0xff3b82f6,
    ports = copyPorts {
      inputs = {
        { id = "in", type = "audio", label = "IN" },
      },
      outputs = {
        { id = "out", type = "audio", label = "OUT" },
      },
      params = {
        { id = "type", label = "Type", path = "/midi/synth/fx2/type",
          min = 0, max = 16, step = 1, default = 0,
          format = "enum",
          options = { "Chorus", "Phaser", "WvShp", "Comp", "Widen", "Filt", "SVF", "Verb", "SDly", "MTap", "Pitch", "Gran", "Ring", "Fmnt", "EQ", "Limit", "Trans" },
          input = true, output = true },
        { id = "mix", label = "Mix", path = "/midi/synth/fx2/mix",
          min = 0, max = 1, step = 0.01, default = 0,
          input = true, output = true },
        { id = "p0", label = "P1", path = "/midi/synth/fx2/p/0",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "p1", label = "P2", path = "/midi/synth/fx2/p/1",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "p2", label = "P3", path = "/midi/synth/fx2/p/2",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "p3", label = "P4", path = "/midi/synth/fx2/p/3",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
        { id = "p4", label = "P5", path = "/midi/synth/fx2/p/4",
          min = 0, max = 1, step = 0.01, default = 0.5,
          input = true, output = true },
      },
    },
    meta = {
      componentId = "fx2Component",
      behavior = "ui/behaviors/fx_slot.lua",
      componentRef = "ui/components/fx_slot.ui.lua",
      slot = 2,
    },
  },
  RackLayout.makeNodeSpec {
    id = "eq",
    name = "EQ8",
    validSizes = { "1x1", "1x2", "2x1" },
    accentColor = 0xff22d3ee,
    ports = copyPorts {
      inputs = {
        { id = "in", type = "audio", label = "IN" },
      },
      outputs = {
        { id = "out", type = "audio", label = "OUT" },
      },
      params = {
        { id = "output", label = "Output", path = "/midi/synth/eq8/output",
          min = -12, max = 12, step = 0.1, default = 0,
          format = "db", input = true, output = true },
        { id = "mix", label = "Mix", path = "/midi/synth/eq8/mix",
          min = 0, max = 1, step = 0.01, default = 1.0,
          input = true, output = true },
        { id = "b1_freq", label = "B1 Freq", path = "/midi/synth/eq8/band/1/freq",
          min = 20, max = 20000, step = 1, default = 60,
          format = "freq", input = true, output = true },
        { id = "b1_gain", label = "B1 Gain", path = "/midi/synth/eq8/band/1/gain",
          min = -18, max = 18, step = 0.1, default = 0,
          format = "db", input = true, output = true },
        { id = "b1_q", label = "B1 Q", path = "/midi/synth/eq8/band/1/q",
          min = 0.1, max = 10, step = 0.1, default = 0.8,
          input = true, output = true },
        { id = "b2_freq", label = "B2 Freq", path = "/midi/synth/eq8/band/2/freq",
          min = 20, max = 20000, step = 1, default = 120,
          format = "freq", input = true, output = true },
        { id = "b2_gain", label = "B2 Gain", path = "/midi/synth/eq8/band/2/gain",
          min = -18, max = 18, step = 0.1, default = 0,
          format = "db", input = true, output = true },
        { id = "b2_q", label = "B2 Q", path = "/midi/synth/eq8/band/2/q",
          min = 0.1, max = 10, step = 0.1, default = 1.0,
          input = true, output = true },
        { id = "b3_freq", label = "B3 Freq", path = "/midi/synth/eq8/band/3/freq",
          min = 20, max = 20000, step = 1, default = 250,
          format = "freq", input = true, output = true },
        { id = "b3_gain", label = "B3 Gain", path = "/midi/synth/eq8/band/3/gain",
          min = -18, max = 18, step = 0.1, default = 0,
          format = "db", input = true, output = true },
        { id = "b3_q", label = "B3 Q", path = "/midi/synth/eq8/band/3/q",
          min = 0.1, max = 10, step = 0.1, default = 1.0,
          input = true, output = true },
        { id = "b4_freq", label = "B4 Freq", path = "/midi/synth/eq8/band/4/freq",
          min = 20, max = 20000, step = 1, default = 500,
          format = "freq", input = true, output = true },
        { id = "b4_gain", label = "B4 Gain", path = "/midi/synth/eq8/band/4/gain",
          min = -18, max = 18, step = 0.1, default = 0,
          format = "db", input = true, output = true },
        { id = "b4_q", label = "B4 Q", path = "/midi/synth/eq8/band/4/q",
          min = 0.1, max = 10, step = 0.1, default = 1.0,
          input = true, output = true },
        { id = "b5_freq", label = "B5 Freq", path = "/midi/synth/eq8/band/5/freq",
          min = 20, max = 20000, step = 1, default = 1000,
          format = "freq", input = true, output = true },
        { id = "b5_gain", label = "B5 Gain", path = "/midi/synth/eq8/band/5/gain",
          min = -18, max = 18, step = 0.1, default = 0,
          format = "db", input = true, output = true },
        { id = "b5_q", label = "B5 Q", path = "/midi/synth/eq8/band/5/q",
          min = 0.1, max = 10, step = 0.1, default = 1.0,
          input = true, output = true },
        { id = "b6_freq", label = "B6 Freq", path = "/midi/synth/eq8/band/6/freq",
          min = 20, max = 20000, step = 1, default = 2500,
          format = "freq", input = true, output = true },
        { id = "b6_gain", label = "B6 Gain", path = "/midi/synth/eq8/band/6/gain",
          min = -18, max = 18, step = 0.1, default = 0,
          format = "db", input = true, output = true },
        { id = "b6_q", label = "B6 Q", path = "/midi/synth/eq8/band/6/q",
          min = 0.1, max = 10, step = 0.1, default = 1.0,
          input = true, output = true },
        { id = "b7_freq", label = "B7 Freq", path = "/midi/synth/eq8/band/7/freq",
          min = 20, max = 20000, step = 1, default = 6000,
          format = "freq", input = true, output = true },
        { id = "b7_gain", label = "B7 Gain", path = "/midi/synth/eq8/band/7/gain",
          min = -18, max = 18, step = 0.1, default = 0,
          format = "db", input = true, output = true },
        { id = "b7_q", label = "B7 Q", path = "/midi/synth/eq8/band/7/q",
          min = 0.1, max = 10, step = 0.1, default = 1.0,
          input = true, output = true },
        { id = "b8_freq", label = "B8 Freq", path = "/midi/synth/eq8/band/8/freq",
          min = 20, max = 20000, step = 1, default = 12000,
          format = "freq", input = true, output = true },
        { id = "b8_gain", label = "B8 Gain", path = "/midi/synth/eq8/band/8/gain",
          min = -18, max = 18, step = 0.1, default = 0,
          format = "db", input = true, output = true },
        { id = "b8_q", label = "B8 Q", path = "/midi/synth/eq8/band/8/q",
          min = 0.1, max = 10, step = 0.1, default = 0.8,
          input = true, output = true },
      },
    },
    meta = {
      componentId = "eqComponent",
      behavior = "ui/behaviors/eq.lua",
      componentRef = "ui/components/eq.ui.lua",
    },
  },
  RackLayout.makeNodeSpec {
    id = "placeholder1",
    name = "Placeholder 1",
    validSizes = { "1x2" },
    accentColor = 0xff64748b,
    ports = copyPorts {},
    meta = {
      componentId = "placeholder1Content",
      componentRef = "ui/components/placeholder.ui.lua",
    },
  },
  RackLayout.makeNodeSpec {
    id = "placeholder2",
    name = "Placeholder 2",
    validSizes = { "1x2" },
    accentColor = 0xff64748b,
    ports = copyPorts {},
    meta = {
      componentId = "placeholder2Content",
      componentRef = "ui/components/placeholder.ui.lua",
    },
  },
  RackLayout.makeNodeSpec {
    id = "placeholder3",
    name = "Placeholder 3",
    validSizes = { "1x1" },
    accentColor = 0xff64748b,
    ports = copyPorts {},
    meta = {
      componentId = "placeholder3Content",
      componentRef = "ui/components/placeholder.ui.lua",
    },
  },
}

function M.nodeSpecs()
  local out = {}
  for i = 1, #NODE_SPECS do
    out[i] = RackLayout.makeNodeSpec(NODE_SPECS[i])
  end
  return out
end

function M.nodeSpecById()
  local out = {}
  local specs = M.nodeSpecs()
  for i = 1, #specs do
    out[specs[i].id] = specs[i]
  end
  return out
end

function M.defaultRackState()
  local state = RackLayout.defaultRackState()
  state.nodes = {
    RackLayout.makeNodeInstance { id = "adsr", row = 0, col = 0, w = 1, h = 1, sizeKey = "1x1", meta = { componentId = "envelopeComponent" } },
    RackLayout.makeNodeInstance { id = "oscillator", row = 0, col = 1, w = 2, h = 1, sizeKey = "1x2", meta = { componentId = "oscillatorComponent" } },
    RackLayout.makeNodeInstance { id = "filter", row = 0, col = 3, w = 2, h = 1, sizeKey = "1x2", meta = { componentId = "filterComponent" } },
    RackLayout.makeNodeInstance { id = "fx1", row = 1, col = 0, w = 2, h = 1, sizeKey = "1x2", meta = { componentId = "fx1Component" } },
    RackLayout.makeNodeInstance { id = "fx2", row = 1, col = 2, w = 2, h = 1, sizeKey = "1x2", meta = { componentId = "fx2Component" } },
    RackLayout.makeNodeInstance { id = "eq", row = 1, col = 4, w = 1, h = 1, sizeKey = "1x1", meta = { componentId = "eqComponent" } },
    RackLayout.makeNodeInstance { id = "placeholder1", row = 2, col = 0, w = 2, h = 1, sizeKey = "1x2", meta = { componentId = "placeholder1Content" } },
    RackLayout.makeNodeInstance { id = "placeholder2", row = 2, col = 2, w = 2, h = 1, sizeKey = "1x2", meta = { componentId = "placeholder2Content" } },
    RackLayout.makeNodeInstance { id = "placeholder3", row = 2, col = 4, w = 1, h = 1, sizeKey = "1x1", meta = { componentId = "placeholder3Content" } },
  }
  return state
end

function M.defaultConnections()
  return {
    RackLayout.makeConnectionDescriptor {
      id = "adsr_to_oscillator",
      kind = "control",
      from = { nodeId = "adsr", portId = "env" },
      to = { nodeId = "oscillator", portId = "gate" },
      meta = { visualOnly = true, source = "current-ui" },
    },
    RackLayout.makeConnectionDescriptor {
      id = "oscillator_to_filter",
      kind = "audio",
      from = { nodeId = "oscillator", portId = "out" },
      to = { nodeId = "filter", portId = "in" },
      meta = { source = "fixed-dsp-chain" },
    },
    RackLayout.makeConnectionDescriptor {
      id = "filter_to_fx1",
      kind = "audio",
      from = { nodeId = "filter", portId = "out" },
      to = { nodeId = "fx1", portId = "in" },
      meta = { route = "relay", source = "fixed-dsp-chain" },
    },
    RackLayout.makeConnectionDescriptor {
      id = "fx1_to_fx2",
      kind = "audio",
      from = { nodeId = "fx1", portId = "out" },
      to = { nodeId = "fx2", portId = "in" },
      meta = { source = "fixed-dsp-chain" },
    },
    RackLayout.makeConnectionDescriptor {
      id = "fx2_to_eq",
      kind = "audio",
      from = { nodeId = "fx2", portId = "out" },
      to = { nodeId = "eq", portId = "in" },
      meta = { source = "fixed-dsp-chain" },
    },
  }
end

return M
