-- Settings UI - Pure declarative spec
-- All widgets declared upfront, behavior handles logic and visibility

return {
  id = "root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 720,
  shellLayout = {
    mode = "fill",
    designW = 1280,
    designH = 720,
  },
  style = {
    bg = 0xff0a0f1a,
  },
  behavior = "ui/behaviors/main.lua",
  children = {
    -- Header
    {
      id = "header",
      type = "Panel",
      x = 0,
      y = 0,
      w = 1280,
      h = 44,
      style = {
        bg = 0xff111827,
        border = 0xff1f2937,
        borderWidth = 1,
      },
    },
    {
      id = "title",
      type = "Label",
      x = 12,
      y = 10,
      w = 200,
      h = 24,
      props = { text = "SETTINGS" },
      style = {
        colour = 0xff7dd3fc,
        fontSize = 20,
        fontStyle = FontStyle.bold,
      },
    },

    -- Tab Bar
    {
      id = "tabBar",
      type = "Panel",
      x = 0,
      y = 44,
      w = 1280,
      h = 40,
      style = {
        bg = 0xff0f172a,
      },
    },
    {
      id = "oscTabBtn",
      type = "Button",
      x = 4,
      y = 48,
      w = 316,
      h = 32,
      props = { label = "OSC" },
      style = {
        bg = 0xff2563eb,
        fontSize = 12,
      },
    },
    {
      id = "linkTabBtn",
      type = "Button",
      x = 324,
      y = 48,
      w = 316,
      h = 32,
      props = { label = "Link" },
      style = {
        bg = 0xff1e293b,
        fontSize = 12,
      },
    },
    {
      id = "midiTabBtn",
      type = "Button",
      x = 644,
      y = 48,
      w = 316,
      h = 32,
      props = { label = "MIDI" },
      style = {
        bg = 0xff1e293b,
        fontSize = 12,
      },
    },
    {
      id = "pathsTabBtn",
      type = "Button",
      x = 964,
      y = 48,
      w = 312,
      h = 32,
      props = { label = "Paths" },
      style = {
        bg = 0xff1e293b,
        fontSize = 12,
      },
    },

    -- ==================== OSC TAB CONTENT ====================
    {
      id = "oscContent",
      type = "Panel",
      x = 0,
      y = 88,
      w = 1280,
      h = 632,
      style = {
        bg = 0xff0a0f1a,
      },
      children = {
        {
          id = "oscStatusPanel",
          type = "Panel",
          x = 12,
          y = 12,
          w = 1256,
          h = 48,
          style = {
            bg = 0xff1a2b1a,
            border = 0xff2d4a2d,
            borderWidth = 2,
            radius = 6,
          },
        },
        {
          id = "oscStatusDisplay",
          type = "Label",
          x = 24,
          y = 26,
          w = 1232,
          h = 20,
          props = { text = "Ready" },
          style = {
            colour = 0xff4ade80,
            fontSize = 14,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "oscPanel",
          type = "Panel",
          x = 12,
          y = 76,
          w = 1256,
          h = 80,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "oscLabel",
          type = "Label",
          x = 24,
          y = 84,
          w = 150,
          h = 18,
          props = { text = "OSC (UDP)" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "oscPort",
          type = "NumberBox",
          x = 24,
          y = 112,
          w = 120,
          h = 32,
          props = {
            min = 1024,
            max = 65535,
            step = 1,
            value = 9000,
            label = "Port",
            format = "%d",
          },
          style = {
            colour = 0xff38bdf8,
          },
        },
        {
          id = "oscToggle",
          type = "Toggle",
          x = 1168,
          y = 112,
          w = 88,
          h = 32,
          props = {
            label = "Enabled",
            value = true,
          },
          style = {
            colour = 0xff34d399,
            bg = 0xff1e293b,
          },
        },
        {
          id = "queryPanel",
          type = "Panel",
          x = 12,
          y = 172,
          w = 1256,
          h = 80,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "queryLabel",
          type = "Label",
          x = 24,
          y = 180,
          w = 150,
          h = 18,
          props = { text = "OSCQuery (HTTP)" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "queryPort",
          type = "NumberBox",
          x = 24,
          y = 208,
          w = 120,
          h = 32,
          props = {
            min = 1024,
            max = 65535,
            step = 1,
            value = 9001,
            label = "Port",
            format = "%d",
          },
          style = {
            colour = 0xff38bdf8,
          },
        },
        {
          id = "queryToggle",
          type = "Toggle",
          x = 1168,
          y = 208,
          w = 88,
          h = 32,
          props = {
            label = "Enabled",
            value = true,
          },
          style = {
            colour = 0xff34d399,
            bg = 0xff1e293b,
          },
        },
        {
          id = "oscApplyBtn",
          type = "Button",
          x = 12,
          y = 268,
          w = 1256,
          h = 48,
          props = { label = "APPLY SETTINGS" },
          style = {
            bg = 0xff2563eb,
            fontSize = 14,
          },
        },
      },
    },

    -- ==================== LINK TAB CONTENT ====================
    {
      id = "linkContent",
      type = "Panel",
      x = 0,
      y = 88,
      w = 1280,
      h = 632,
      style = {
        bg = 0xff0a0f1a,
      },
      children = {
        {
          id = "linkStatusPanel",
          type = "Panel",
          x = 12,
          y = 12,
          w = 1256,
          h = 60,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "linkStatusLabel",
          type = "Label",
          x = 24,
          y = 20,
          w = 150,
          h = 20,
          props = { text = "Ableton Link" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 14,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "linkPeersLabel",
          type = "Label",
          x = 24,
          y = 44,
          w = 150,
          h = 20,
          props = { text = "0 peers" },
          style = {
            colour = 0xff64748b,
            fontSize = 12,
          },
        },
        {
          id = "linkSettingsPanel",
          type = "Panel",
          x = 12,
          y = 88,
          w = 1256,
          h = 140,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "linkSettingsLabel",
          type = "Label",
          x = 24,
          y = 96,
          w = 120,
          h = 18,
          props = { text = "Link Settings" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "linkToggle",
          type = "Toggle",
          x = 24,
          y = 124,
          w = 140,
          h = 28,
          props = {
            label = "Link Enabled",
            value = true,
          },
          style = {
            colour = 0xfff59e0b,
            bg = 0xff1e293b,
          },
        },
        {
          id = "linkTempoToggle",
          type = "Toggle",
          x = 24,
          y = 160,
          w = 140,
          h = 28,
          props = {
            label = "Tempo Sync",
            value = true,
          },
          style = {
            colour = 0xff38bdf8,
            bg = 0xff1e293b,
          },
        },
        {
          id = "linkStartStopToggle",
          type = "Toggle",
          x = 172,
          y = 160,
          w = 150,
          h = 28,
          props = {
            label = "Start/Stop Sync",
            value = true,
          },
          style = {
            colour = 0xffa78bfa,
            bg = 0xff1e293b,
          },
        },
        {
          id = "linkTempoPanel",
          type = "Panel",
          x = 12,
          y = 244,
          w = 1256,
          h = 80,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "linkTempoLabel",
          type = "Label",
          x = 24,
          y = 252,
          w = 120,
          h = 18,
          props = { text = "Current Tempo" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "linkTempoDisplay",
          type = "Label",
          x = 24,
          y = 280,
          w = 200,
          h = 30,
          props = { text = "120.0 BPM" },
          style = {
            colour = 0xff38bdf8,
            fontSize = 24,
            fontStyle = FontStyle.bold,
          },
        },
      },
    },

    -- ==================== PATHS TAB CONTENT ====================
    {
      id = "pathsContent",
      type = "Panel",
      x = 0,
      y = 88,
      w = 1280,
      h = 632,
      style = {
        bg = 0xff0a0f1a,
      },
      children = {
        {
          id = "userDirPanel",
          type = "Panel",
          x = 12,
          y = 12,
          w = 1256,
          h = 140,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "userDirLabel",
          type = "Label",
          x = 24,
          y = 20,
          w = 200,
          h = 18,
          props = { text = "User Scripts Directory" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "userDirPathLabel",
          type = "Label",
          x = 24,
          y = 44,
          w = 1232,
          h = 40,
          props = { text = "Not set (click Browse to configure)" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 10,
          },
        },
        {
          id = "browseUserDirBtn",
          type = "Button",
          x = 24,
          y = 107,
          w = 100,
          h = 28,
          props = { label = "Browse..." },
          style = {
            bg = 0xff2563eb,
            fontSize = 11,
          },
        },
        {
          id = "clearUserDirBtn",
          type = "Button",
          x = 1168,
          y = 107,
          w = 80,
          h = 28,
          props = { label = "Clear" },
          style = {
            bg = 0xff7f1d1d,
            fontSize = 11,
          },
        },
        {
          id = "devDirPanel",
          type = "Panel",
          x = 12,
          y = 168,
          w = 1256,
          h = 80,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "devDirLabel",
          type = "Label",
          x = 24,
          y = 176,
          w = 250,
          h = 18,
          props = { text = "Development Scripts Directory" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "devDirPathLabel",
          type = "Label",
          x = 24,
          y = 200,
          w = 1232,
          h = 40,
          props = { text = "Not configured" },
          style = {
            colour = 0xff64748b,
            fontSize = 10,
          },
        },
        {
          id = "dspDirPanel",
          type = "Panel",
          x = 12,
          y = 264,
          w = 1256,
          h = 140,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "dspDirLabel",
          type = "Label",
          x = 24,
          y = 272,
          w = 200,
          h = 18,
          props = { text = "DSP Scripts Directory" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "dspDirPathLabel",
          type = "Label",
          x = 24,
          y = 296,
          w = 1232,
          h = 40,
          props = { text = "Not set (click Browse to configure)" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 10,
          },
        },
        {
          id = "browseDspDirBtn",
          type = "Button",
          x = 24,
          y = 359,
          w = 100,
          h = 28,
          props = { label = "Browse..." },
          style = {
            bg = 0xff2563eb,
            fontSize = 11,
          },
        },
        {
          id = "clearDspDirBtn",
          type = "Button",
          x = 1168,
          y = 359,
          w = 80,
          h = 28,
          props = { label = "Clear" },
          style = {
            bg = 0xff7f1d1d,
            fontSize = 11,
          },
        },
      },
    },

    -- ==================== MIDI TAB CONTENT ====================
    {
      id = "midiContent",
      type = "Panel",
      x = 0,
      y = 88,
      w = 1280,
      h = 632,
      style = {
        bg = 0xff0a0f1a,
      },
      children = {
        {
          id = "midiInputPanel",
          type = "Panel",
          x = 12,
          y = 12,
          w = 1256,
          h = 100,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "midiInputLabel",
          type = "Label",
          x = 24,
          y = 20,
          w = 200,
          h = 18,
          props = { text = "MIDI Input Device" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "midiInputDropdown",
          type = "Dropdown",
          x = 24,
          y = 48,
          w = 1156,
          h = 36,
          props = {
            options = { "None (Use Host MIDI)" },
            selected = 1,
          },
          style = {
            bg = 0xff1e293b,
            colour = 0xff38bdf8,
          },
        },
        {
          id = "midiRefreshInputBtn",
          type = "Button",
          x = 1188,
          y = 48,
          w = 68,
          h = 36,
          props = { label = "Refresh" },
          style = {
            bg = 0xff0f3460,
            fontSize = 10,
          },
        },
        {
          id = "midiOutputPanel",
          type = "Panel",
          x = 12,
          y = 124,
          w = 1256,
          h = 100,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "midiOutputLabel",
          type = "Label",
          x = 24,
          y = 132,
          w = 200,
          h = 18,
          props = { text = "MIDI Output Device" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "midiOutputDropdown",
          type = "Dropdown",
          x = 24,
          y = 160,
          w = 1232,
          h = 36,
          props = {
            options = { "None (Disabled)" },
            selected = 1,
          },
          style = {
            bg = 0xff1e293b,
            colour = 0xff38bdf8,
          },
        },
        {
          id = "midiSettingsPanel",
          type = "Panel",
          x = 12,
          y = 236,
          w = 1256,
          h = 140,
          style = {
            bg = 0xff141a24,
            radius = 8,
          },
        },
        {
          id = "midiSettingsLabel",
          type = "Label",
          x = 24,
          y = 244,
          w = 120,
          h = 18,
          props = { text = "MIDI Settings" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "midiOmniToggle",
          type = "Toggle",
          x = 24,
          y = 272,
          w = 140,
          h = 28,
          props = {
            label = "Omni Mode",
            value = true,
          },
          style = {
            colour = 0xfff59e0b,
            bg = 0xff1e293b,
          },
        },
        {
          id = "midiThruToggle",
          type = "Toggle",
          x = 172,
          y = 272,
          w = 140,
          h = 28,
          props = {
            label = "MIDI Thru",
            value = false,
          },
          style = {
            colour = 0xff34d399,
            bg = 0xff1e293b,
          },
        },
        {
          id = "midiTestBtn",
          type = "Button",
          x = 24,
          y = 316,
          w = 120,
          h = 36,
          props = { label = "Send Test Note" },
          style = {
            bg = 0xff2563eb,
            fontSize = 11,
          },
        },
        {
          id = "midiPanicBtn",
          type = "Button",
          x = 152,
          y = 316,
          w = 120,
          h = 36,
          props = { label = "All Notes Off" },
          style = {
            bg = 0xff7f1d1d,
            fontSize = 11,
          },
        },
        {
          id = "midiMonitorPanel",
          type = "Panel",
          x = 12,
          y = 392,
          w = 1256,
          h = 80,
          style = {
            bg = 0xff1a2b1a,
            border = 0xff2d4a2d,
            borderWidth = 2,
            radius = 4,
          },
        },
        {
          id = "midiMonitorLabel",
          type = "Label",
          x = 24,
          y = 400,
          w = 120,
          h = 18,
          props = { text = "MIDI Monitor" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 12,
            fontStyle = FontStyle.bold,
          },
        },
        {
          id = "midiActivityLed",
          type = "Panel",
          x = 1228,
          y = 404,
          w = 16,
          h = 16,
          style = {
            bg = 0xff333333,
            radius = 8,
          },
        },
        {
          id = "midiEventDisplay",
          type = "Label",
          x = 24,
          y = 432,
          w = 1232,
          h = 24,
          props = { text = "Waiting for MIDI..." },
          style = {
            colour = 0xff4ade80,
            fontSize = 13,
            fontStyle = FontStyle.bold,
          },
        },
      },
    },
  },
}
