return {
  inputDevice = "MPK Mini Mk II MIDI 1",
  keyboardCollapsed = false,
  keyboardKeyCount = 14,
  utilityDockVisible = true,
  utilityDockMode = "keyboard",
  utilityDockHeightMode = "compact",
  rackViewMode = "perf",
  rackDensityMode = "normal",
  rackNodes = {},
  rackConnections = {
  { id="oscillator_to_filter", kind="audio", from={ moduleId="oscillator", portId="out" }, to={ moduleId="filter", portId="in" }, meta={ source="fixed-dsp-chain" } },
  { id="filter_to_fx1", kind="audio", from={ moduleId="filter", portId="out" }, to={ moduleId="fx1", portId="in" }, meta={ route="relay", source="fixed-dsp-chain" } },
  { id="fx1_to_fx2", kind="audio", from={ moduleId="fx1", portId="out" }, to={ moduleId="fx2", portId="in" }, meta={ source="fixed-dsp-chain" } },
  { id="fx2_to_eq", kind="audio", from={ moduleId="fx2", portId="out" }, to={ moduleId="eq", portId="in" }, meta={ route="relay", source="fixed-dsp-chain" } },
  { id="eq_to_output", kind="audio", from={ moduleId="eq", portId="out" }, to={ moduleId="__rackOutput", portId="main" }, meta={ route="output", source="fixed-dsp-chain" } },
},
  waveform = 1,
  filterType = 0,
  cutoff = 3200.00,
  resonance = 0.750,
  drive = 0.00,
  driveShape = 0,
  driveBias = 0.000,
  output = 0.800,
  attack = 0.0500,
  decay = 0.2000,
  sustain = 0.700,
  release = 0.4000,
  fx1Type = 0,
  fx1Mix = 0.000,
  fx2Type = 0,
  fx2Mix = 0.000,
  oscMode = 0,
  sampleSource = 0,
  sampleCaptureBars = 1.0000,
  samplePitchMapEnabled = false,
  samplePitchMode = 0,
  sampleRootNote = 60.00,
  samplePlayStart = 0.0000,
  sampleLoopStart = 0.0000,
  sampleLoopLen = 1.0000,
  sampleRetrigger = 1,
  blendMode = 0,
  blendAmount = 0.500,
  waveToSample = 0.500,
  sampleToWave = 0.000,
  blendKeyTrack = 2,
  blendSamplePitch = 0.00,
  blendModAmount = 0.500,
  envFollow = 1.000,
  addFlavor = 0,
  xorBehavior = 0,
  delayMix = 0.000,
  delayTime = 0,
  delayFeedback = 0.000,
  reverbWet = 0.000,
  pulseWidth = 0.50,
  unison = 1,
  detune = 0.0,
  spread = 0.00,
  oscRenderMode = 0,
  additivePartials = 8,
  additiveTilt = 0.000,
  additiveDrift = 0.000,
}